# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.2
    hooks:
    -   id: ruff
        args: ["--exclude", "docs"]
-   repo: https://github.com/jackdewinter/pymarkdown
    rev:  v0.9.12
    hooks:
    -   id: pymarkdown
        exclude: |
            (?x)^(
                docs/.*|
                .gitlab/.*|
            )$

